---
version: '2'
services:
  nzbget:
    image: linuxserver/nzbget:version-v21.1
    container_name: nzbget
    volumes:
      - "/mnt/APPS/nzbget:/config"
      - "/mnt/MEDIA/Downloads:/downloads"
      - "/mnt/MEDIA/Downloads/complete:/downloads/complete"
    ports:
      - 27020:6789
    environment:
      - PUID=500
      - PGID=100
  sonarr:
    image: linuxserver/sonarr:4.0.15
    # image: linuxserver/sonarr
    container_name: sonarr
    security_opt:
      - seccomp:unconfined
    depends_on:
      - nzbget
    volumes:
      - "/mnt/APPS/sonarr:/config"
      - "/mnt/MEDIA/TV:/tv"
      - "/mnt/MEDIA/Downloads/complete/Series:/downloads"
    ports:
      - 27021:8989
    links:
      - nzbget
    environment:
      - PUID=500
      - PGID=100
  radarr:
    image: linuxserver/radarr:5.27.5
    container_name: radarr
    depends_on:
      - nzbget
    volumes:
      - "/mnt/APPS/radarr:/config"
      - "/mnt/MEDIA/Movies:/movies"
      - "/mnt/MEDIA/Downloads/complete/Movies:/downloads"
    ports:
      - 27022:7878
    links:
      - nzbget
    environment:
      - PUID=500
      - PGID=100
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    volumes:
      - "/home/tim/PlexConfig:/config"
      - "/mnt/MEDIA/Transcode:/transcode"
      - "/mnt/MEDIA:/data"
    network_mode: host
    hostname: fairweatherflix
    environment:
      - TZ="America/Eastern"
      - PUID=500
      - PGID=100
    devices:
      - /dev/dri:/dev/dri
#  plexpy:
#    image: linuxserver/plexpy
#    container_name: plexpy
#    depends_on:
#      - plex
#    volumes:
#      - "/mnt/MEDIA/appdata/plexpy:/config"
#      - "/home/tim/PlexConfig/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro"
#    ports:
#      - 27023:8181
#    links:
#      - plex
#    environment:
#      - PUID=500
#      - PGID=100
  tautulli:
    image: linuxserver/tautulli:2.16.0
    container_name: tautulli
    depends_on:
      - plex
    volumes:
      - "/mnt/APPS/tautulli:/config"
      - "/home/tim/PlexConfig/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro"
    ports:
      - 27023:8181
    links:
      - plex
    environment:
      - PUID=500
      - PGID=100
  ombi:
    image: linuxserver/ombi:4.47.1
    container_name: ombi
    depends_on:
      - plex
    volumes:
      - "/mnt/MEDIA/appdata/ombi:/config"
    ports:
      - 27024:3579
    links:
      - plex
    environment:
      - PUID=500
      - PGID=100
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=500
      - PGID=100
      - URL=thefairweathers.ca
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare #optional
      - EMAIL=tim@thefairweathers.ca
      - STAGING=false
    volumes:
      - /mnt/APPS/swag:/config
    ports:
      - 443:443
      - 80:80 #optional
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=500
      - PGID=100
    volumes:
      - /mnt/APPS/ddclient:/config
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ="America/Eastern"
      - PUID=500
      - PGID=100
    network_mode: host
    volumes:
      - /mnt/APPS/homeassistant:/config
  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    network_mode: host
    environment:
      - TZ="America/Eastern"
      - PGID=100
      - PUID=500
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - /mnt/APPS/homebridge:/homebridge
#  proxy:
#    image: nginx:latest
#    container_name: proxy
#    depends_on:
#      - ombi
#    volumes:
#      - "./nginx.conf:/etc/nginx/nginx.conf"
#      - "/mnt/MEDIA/certs/condo.thefairweathers.ca/:/etc/letsencrypt/"
#    ports:
#      - 80:80
#      - 443:443
#  certbot:
#    image: certbot/dns-cloudflare:latest
#    container_name: certs
#    volumes:
#      - "/mnt/MEDIA/certbot/etc/:/etc/letsencrypt/"
#      - "/mnt/MEDIA/certbot/lib/:/var/lib/letsencrypt/"
#      - "/mnt/MEDIA/certbot/log/:/var/log/letsencrypt/"
#    environment:
#      - PUID=500
#      - PGID=100

