---
services:
  nzbget:
    image: linuxserver/nzbget:version-v21.1
    container_name: nzbget
    restart: unless-stopped
    volumes:
      - "/mnt/APPS/nzbget:/config"
      - "/mnt/MEDIA/Downloads:/downloads"
      - "/mnt/MEDIA/Downloads/complete:/downloads/complete"
    ports:
      - 27020:6789
    environment:
      - PUID=500
      - PGID=100
  sonarr:
    image: linuxserver/sonarr:4.0.15
    # image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    depends_on:
      - nzbget
    volumes:
      - "/mnt/APPS/sonarr:/config"
      - "/mnt/MEDIA/TV:/tv"
      - "/mnt/MEDIA/Downloads/complete/Series:/downloads"
    ports:
      - 27021:8989
    links:
      - nzbget
    environment:
      - PUID=500
      - PGID=100
  radarr:
    image: linuxserver/radarr:5.27.5
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - nzbget
    volumes:
      - "/mnt/APPS/radarr:/config"
      - "/mnt/MEDIA/Movies:/movies"
      - "/mnt/MEDIA/Downloads/complete/Movies:/downloads"
    ports:
      - 27022:7878
    links:
      - nzbget
    environment:
      - PUID=500
      - PGID=100
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    restart: unless-stopped
    volumes:
      - "/home/tim/PlexConfig:/config"
      - "/mnt/MEDIA/Transcode:/transcode"
      - "/mnt/MEDIA:/data"
    network_mode: host
    hostname: fairweatherflix
    environment:
      - TZ="America/Eastern"
      - PUID=500
      - PGID=100
    devices:
      - /dev/dri:/dev/dri
  tautulli:
    image: linuxserver/tautulli:2.16.0
    container_name: tautulli
    restart: unless-stopped
    depends_on:
      - plex
    volumes:
      - "/mnt/APPS/tautulli:/config"
      - "/home/tim/PlexConfig/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro"
    ports:
      - 27023:8181
    links:
      - plex
    environment:
      - PUID=500
      - PGID=100
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      - TZ="America/Eastern"
      - PUID=500
      - PGID=100
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /mnt/APPS/overseerr:/app/config
  ombi:
    image: linuxserver/ombi:4.47.1
    container_name: ombi
    restart: unless-stopped
    depends_on:
      - plex
    volumes:
      - "/mnt/APPS/ombi:/config"
    ports:
      - 27024:3579
    links:
      - plex
    environment:
      - PUID=500
      - PGID=100
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=500
      - PGID=100
      - URL=thefairweathers.ca
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare #optional
      - EMAIL=tim@thefairweathers.ca
      - STAGING=false
    volumes:
      - /mnt/APPS/swag:/config
    ports:
      - 443:443
      - 80:80 #optional
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    restart: unless-stopped
    environment:
      - PUID=500
      - PGID=100
    volumes:
      - /mnt/APPS/ddclient:/config
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - TZ="America/Eastern"
      - PUID=500
      - PGID=100
    network_mode: host
    volumes:
      - /mnt/APPS/homeassistant:/config
  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ="America/Eastern"
      - PGID=100
      - PUID=500
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - /mnt/APPS/homebridge:/homebridge
  tdarr:
    image: haveagitgat/tdarr
    container_name: tdarr
    restart: unless-stopped
    ports:
      - "8265:8265" # WebUI
      - "8266:8266" # Node communications
    environment:
      - TZ="America/Eastern"
      - PUID=500
      - PGID=100
      - serverIP=10.88.111.202 # Or your server's IP
      - serverPort=8266
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=7
      - nodeName=Krypton
      - nodeHardwareEncoding=true
      - LIBVA_DRIVER_NAME=iHD              # use the modern Intel media driver
      - FFMPEG_HWACCEL_ARGS=-hwaccel qsv -qsv_device /dev/dri/renderD128
    volumes:
      - /mnt/APPS/tdarr/server:/app/server
      - /mnt/APPS/tdarr/logs:/app/logs
      - /mnt/APPS/tdarr/configs:/app/configs
      - /mnt/MEDIA:/media # Your media library
      - /mnt/tdarr-cache:/temp # Transcode cache
      # Optional: Specify Intel QSV for FFMPEG
      # - FFMPEG_HWACCEL_ARGS=-hwaccel qsv -qsv_device /dev/dri/renderD128 
      #    devices:
      #- /dev/dri:/dev/dri # Expose Intel iGPU devices
    group_add:       
      - "44"
      - "993"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=automate.thefairweathers.ca
      - N8N_PORT=5678
      - N8N_RUNNERS_ENABLED=true
      - N8N_PROXY_HOPS=1
      - N8N_PROTOCOL=http
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=smtp-relay.brevo.com
      - N8N_SMTP_PORT=587
      - N8N_SMTP_USER=${SMTP_USER}
      - N8N_SMTP_PASS=${SMTP_PASSWORD}
      - N8N_SMTP_SENDER="n8n <noreply@thefairweathers.ca>"
      - N8N_SMTP_SSL=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=${N8N_DB_USER}
      - DB_POSTGRESDB_PASSWORD=${N8N_DB_PASSWORD}
      - NODE_ENV=production
      - WEBHOOK_URL=https://automate.thefairweathers.ca
      - N8N_EDITOR_BASE_URL=https://automate.thefairweathers.ca
      - TZ="America/Eastern"
      - PUID=500
      - PGID=100
      # - N8N_LOG_LEVEL=debug
    volumes:
      - /mnt/APPS/n8n:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=${N8N_DB_USER}
      - POSTGRES_PASSWORD=${N8N_DB_PASSWORD}
      - TZ="America/Eastern"
      - PUID=500
      - PGID=100
    volumes:
      - /mnt/n8n-pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n"]
      interval: 10s
      timeout: 5s
      retries: 5
