---
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443" # HTTPS UI
      - "8000:8000" # Edge agent communications
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/mnt/APPS/portainer:/data"
